### ISSUE TITLE
Hydro 4.16.0 以上插件无法加载

### ISSUE THREAD

**Issue by mywwzh** [open33oj/hydro-plugins#5]
Hydro 4.16.0 / UI 4.54.3  更新内容：

- core: 停用 handler, lib, script 组件类型

这导致 `Handler load fail: /xxxxxxxxx/hydro-plugins/pastebin-33oj`。

**Comment by wood3** [comment]
已修复

**Comment by wood3** [comment]
已修复

**Comment by laoshuikaixue** [comment]
> 已修复

countdown仍然无法工作

**Comment by wood3** [comment]
> > 已修复
> 
> countdown仍然无法工作

看起来只是你没有安装  moment ？我这边运行良好：https://oj.33dai.cn/
